# Minima theme configuration
remote_theme: minima
plugins:
- jekyll-remote-theme

minima:
  skin: dark

title: brittni - coding nerd
description: (sher/her) i love to make awesome things with code! ğŸ’•ğŸ‘©ğŸ½â€ğŸ’»
show_downloads: false
