# Minima theme configuration
remote_theme: jekyll/minima
plugins:
- jekyll-remote-theme

minima:
  skin: auto
  social_links:
    - title: GitHub
      icon: github
      url: "https://github.com/blwatkins"
    - title: Jekyll at X (formerly Twitter)
      icon: x-twitter
      url: "https://x.com/books_n_code"

author:
  name: brittni | coding nerd

title: brittni - coding nerd
description: i love to make awesome things with code! ğŸ’•ğŸ‘©ğŸ½â€ğŸ’»
show_downloads: false
