# Minima theme configuration
remote_theme: jekyll/minima
plugins:
- jekyll-remote-theme

minima:
  skin: auto

author:
  name: brittni | coding nerd

title: brittni - coding nerd
description: i love to make awesome things with code! ğŸ’•ğŸ‘©ğŸ½â€ğŸ’»
show_downloads: false
